# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cryptosporidium_host_adaptation',
                'doc_host': 'https://mtinti.github.io',
                'git_url': 'https://github.com/mtinti/cryptosporidium_host_adaptation',
                'lib_path': 'cryptosporidium_host_adaptation'},
  'syms': {'cryptosporidium_host_adaptation.core': {}}}
