name: CI
on: [workflow_dispatch, pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install samtools
        run: |
          sudo apt-get update
          sudo apt-get install -y samtools
          sudo apt-get install -y bcftools
      
      - uses: fastai/workflows/nbdev-ci@master
